/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package footballplayerposition;

/**
 *
 * @author Jonathan
 */
public class InfoLayout extends javax.swing.JFrame {

    /**
     * Creates new form InfoLayout
     */
    public InfoLayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        bgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(960, 750));
        setResizable(false);
        getContentPane().setLayout(null);

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setBorderPainted(false);
        backButton.setOpaque(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(20, 660, 60, 50);

        bgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/footballplayerposition/uiketiga.jpg"))); // NOI18N
        getContentPane().add(bgLabel);
        bgLabel.setBounds(0, -20, 970, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        MainLayout mainLayout = new MainLayout();
        mainLayout.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_backButtonActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        showInfo();
    }        
    /**
     * @param args the command line arguments
     */
    public static void showInfo() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoLayout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel bgLabel;
    // End of variables declaration//GEN-END:variables
}
