/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package footballplayerposition;

/**
 *
 * @author User
 */
public class ResultLayout extends javax.swing.JFrame {

    /**
     * Creates new form ResultLayout
     */
    public ResultLayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        defenceScoreLabel = new javax.swing.JLabel();
        centerScoreLabel = new javax.swing.JLabel();
        strikerScoreLabel = new javax.swing.JLabel();
        bgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(960, 750));
        setResizable(false);
        getContentPane().setLayout(null);

        defenceScoreLabel.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        getContentPane().add(defenceScoreLabel);
        defenceScoreLabel.setBounds(270, 470, 120, 40);

        centerScoreLabel.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        getContentPane().add(centerScoreLabel);
        centerScoreLabel.setBounds(270, 380, 120, 40);

        strikerScoreLabel.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        getContentPane().add(strikerScoreLabel);
        strikerScoreLabel.setBounds(270, 290, 120, 40);

        bgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/footballplayerposition/uikedua.jpg"))); // NOI18N
        bgLabel.setPreferredSize(new java.awt.Dimension(960, 750));
        getContentPane().add(bgLabel);
        bgLabel.setBounds(0, 0, 960, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultLayout().setVisible(true);
            }
        });  
    }
    
    public void showResult() {
    strikerScoreLabel.setText(Double.toString(strikerScore));
    centerScoreLabel.setText(Double.toString(centerScore));
    defenceScoreLabel.setText(Double.toString(defenceScore));
}

    public double strikerScore;
    public double centerScore;
    public double defenceScore;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgLabel;
    private javax.swing.JLabel centerScoreLabel;
    private javax.swing.JLabel defenceScoreLabel;
    private javax.swing.JLabel strikerScoreLabel;
    // End of variables declaration//GEN-END:variables
}
