/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package footballplayerposition;

import footballplayerposition.MainLayout;
/**
 *
 * @author User
 */
public class ResultLayout extends javax.swing.JFrame {

    /**
     * Creates new form ResultLayout
     */
    public ResultLayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        nationLabel = new javax.swing.JLabel();
        numberLabel = new javax.swing.JLabel();
        footLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        phyLabel = new javax.swing.JLabel();
        defLabel = new javax.swing.JLabel();
        dribLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        shootLabel = new javax.swing.JLabel();
        accLabel = new javax.swing.JLabel();
        defenceScoreLabel = new javax.swing.JLabel();
        centerScoreLabel = new javax.swing.JLabel();
        strikerScoreLabel = new javax.swing.JLabel();
        bgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(960, 750));
        setResizable(false);
        getContentPane().setLayout(null);

        nameLabel.setFont(new java.awt.Font("SansSerif", 1, 45)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Name");
        getContentPane().add(nameLabel);
        nameLabel.setBounds(570, 50, 270, 50);

        nationLabel.setFont(new java.awt.Font("SansSerif", 0, 19)); // NOI18N
        nationLabel.setForeground(new java.awt.Color(255, 255, 255));
        nationLabel.setText("Nationality");
        getContentPane().add(nationLabel);
        nationLabel.setBounds(570, 90, 150, 40);

        numberLabel.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        numberLabel.setForeground(new java.awt.Color(255, 255, 255));
        numberLabel.setText("No");
        getContentPane().add(numberLabel);
        numberLabel.setBounds(570, 130, 50, 40);

        footLabel.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        footLabel.setForeground(new java.awt.Color(255, 255, 255));
        footLabel.setText("Foot");
        getContentPane().add(footLabel);
        footLabel.setBounds(630, 130, 100, 40);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setBorderPainted(false);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(780, 50, 140, 120);

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setBorderPainted(false);
        backButton.setOpaque(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(20, 663, 60, 50);

        phyLabel.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        phyLabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(phyLabel);
        phyLabel.setBounds(800, 470, 60, 40);

        defLabel.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        defLabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(defLabel);
        defLabel.setBounds(800, 380, 60, 40);

        dribLabel.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        dribLabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(dribLabel);
        dribLabel.setBounds(800, 290, 60, 40);

        passLabel.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        passLabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(passLabel);
        passLabel.setBounds(630, 470, 60, 40);

        shootLabel.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        shootLabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(shootLabel);
        shootLabel.setBounds(630, 380, 60, 40);

        accLabel.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        accLabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(accLabel);
        accLabel.setBounds(630, 290, 60, 40);

        defenceScoreLabel.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        getContentPane().add(defenceScoreLabel);
        defenceScoreLabel.setBounds(270, 470, 120, 40);

        centerScoreLabel.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        getContentPane().add(centerScoreLabel);
        centerScoreLabel.setBounds(270, 380, 120, 40);

        strikerScoreLabel.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        getContentPane().add(strikerScoreLabel);
        strikerScoreLabel.setBounds(270, 290, 120, 40);

        bgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/footballplayerposition/uikedua.jpg"))); // NOI18N
        bgLabel.setPreferredSize(new java.awt.Dimension(960, 750));
        getContentPane().add(bgLabel);
        bgLabel.setBounds(0, 0, 960, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        showResult();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        MainLayout mainLayout = new MainLayout();
        mainLayout.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }
    
    public void showResult() {
    strikerScoreLabel.setText(Double.toString(strikerScore));
    centerScoreLabel.setText(Double.toString(centerScore));
    defenceScoreLabel.setText(Double.toString(defenceScore));
    
    accLabel.setText(Double.toString(playerStat[0]));
    shootLabel.setText(Double.toString(playerStat[1]));
    passLabel.setText(Double.toString(playerStat[2]));
    dribLabel.setText(Double.toString(playerStat[3]));
    defLabel.setText(Double.toString(playerStat[4]));
    phyLabel.setText(Double.toString(playerStat[5]));
    
    nameLabel.setText(name);
    nationLabel.setText(nation);
    numberLabel.setText(number);
    footLabel.setText(foot);
}

    public double strikerScore;
    public double centerScore;
    public double defenceScore;
    
    public String name;
    public String nation;
    public String number;
    public String foot;
    
    public double[] playerStat;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel bgLabel;
    private javax.swing.JLabel centerScoreLabel;
    private javax.swing.JLabel defLabel;
    private javax.swing.JLabel defenceScoreLabel;
    private javax.swing.JLabel dribLabel;
    private javax.swing.JLabel footLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nationLabel;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JLabel passLabel;
    private javax.swing.JLabel phyLabel;
    private javax.swing.JLabel shootLabel;
    private javax.swing.JLabel strikerScoreLabel;
    // End of variables declaration//GEN-END:variables
}
